### ISSUE TITLE
Schools without program data not working with API refactor

### ISSUE THREAD

**Issue by niqjohnson** [cfpb/college-costs#120]
The API refactor in #118 works great for schools with program data but fails for me for schools without program data. For example: `/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=234155#info-right`

Since there's no program data associated with that school, some content on the page (the graphs, especially) doesn't display. I've only poked around a little, but it looks like some JS isn't getting executed in those cases. Putting a `console.log` at the very top of `metricView.init`, for instance, prints a console message for our test school with program data but not for any other school.

**Comment by mistergone** [comment]
I believe this is due to API calls that result in uncaught errors. Error handling on the API calls needs to be improved.

I'll fix it next chance I get.

![fixed-it](https://cloud.githubusercontent.com/assets/1490703/13431571/fd36ce1c-df97-11e5-829b-c650fabd1a87.gif)

**Comment by marteki** [comment]
Addressed in PR https://github.com/cfpb/college-costs/pull/185!
