### ISSUE TITLE
Six-digit values overlap dollar signs in line items

### ISSUE THREAD

**Issue by niqjohnson** [cfpb/college-costs#130]
Six-digit values (and negative five-digit values to a lesser degree) overlap the dollar sign in line items:

![six-digit-debt](https://cloud.githubusercontent.com/assets/1862695/13360716/73af1d00-dc88-11e5-8a94-2a9d7f4b05bf.png)

This one's totally my fault—I intentionally set the dollar sign far enough over to fit five digits plus a comma, thinking "no one's going to take out $100,000 of loans for a year!" But I forgot that we also show total debt for the entire program, which could conceivably be six digits.

Not sure what the best solution is here, but note that if we end up moving the dollar sign over for six-digit values, we'll need to check to make sure it fits across all screen sizes (the accounting column is already pretty tight for screen sizes near the smaller breakpoints).

**Comment by marteki** [comment]
Addressed in PR https://github.com/cfpb/college-costs/pull/183!
