### ISSUE TITLE
percentage box prevents entering decimal value

### ISSUE THREAD

**Issue by higs4281** [cfpb/college-costs#141]
From user testing: When entering a new value for private loan interest, after typing a number and a decimal point, the tool _sometimes_ won't allow entry of a value after the decimal.

**Comment by marteki** [comment]
@mistergone, was this specific issue addressed in PR https://github.com/cfpb/college-costs/pull/182?

**Comment by mistergone** [comment]
No, the bug as reported in this issue is one I was never able to reproduce, so I think it was addressed accidentally somewhere else. I did try to reproduce it when working on #182, but was never able to.

**Comment by higs4281** [comment]
Can't reproduce. Closing.
