### ISSUE TITLE
Functional test scenarios

### ISSUE THREAD

**Issue by marteki** [cfpb/college-costs#24]
The scenarios that will drive Javascript development for the "understanding financial aid offers" page

Separated by audience:
- [x] Specific to settlement students
- [x] Specific to non-settlement students
- [x] Used by all students

**Comment by marteki** [comment]
# Settlement student functional test scenarios

> As a settlement student,
> I want to verify my financial aid offer information

### Scenario: Settlement student accesses personalized financial aid offer URL

Given the page URL contains aid offer variables
When the page is loaded
Then ensure the section for verifying an aid offer is displayed

### Scenario: Settlement student reports incorrect aid offer information

Given the page URL contains aid offer variables
When the student reports that the aid offer information is not theirs
Then ensure the student is informed about contacting the school
And ensure the school is notified about the incorrect aid offer

### Scenario: Settlement student confirms correct aid offer information

Given the page URL contains aid offer variables
When the student confirms that the aid offer information is theirs
Then ensure the section for reviewing the aid offer is displayed
And ensure all the cost of attendance fields are pre-populated
And ensure the graduation rate graph is populated
And ensure the average salary after graduation graph is populated
And ensure the estimated monthly living expenses are populated
And ensure the debt burden equation is populated
And ensure the total debt after graduation graph is populated
And ensure the loan default rate graph is populated

**Comment by marteki** [comment]
# Non-settlement student functional test scenarios

> As a non-settlement student,
> I want to enter my school and program information

### Scenario: Student accesses non-personalized financial aid offers URL

Given the page URL does not contain aid offer variables
When the page is loaded
Then ensure the section for searching to select a school is displayed

### Scenario: Student searches for a school in the database

Given the page URL does not contain aid offer variables
When a student start to search for a school
Then ensure the list of possible schools is displayed

### Scenario: Student selects a school from the database

Given the page URL does not contain aid offer variables
When a student selects a school from the list of school search results
Then ensure the student is asked about having an existing financial aid offer
And ensure the student is asked about their degree type
And ensure the student is asked about their program length
And ensure that if applicable, the student is asked about their residency status
And ensure the student is asked about their housing situation

### Scenario: Student already has a financial aid offer

Given the page URL does not contain aid offer variables
When a student has an existing financial aid offer
Then ensure the student is told to fill out the page using that aid offer

### Scenario: Student gives all needed information for a school in the database

Given the page URL does not contain aid offer variables
When a student selects a school from the list of school search results
And a student chooses their degree type
And a student chooses their program length
And if applicable, the student chooses their residency status
And a student chooses their housing
Then ensure the section for reviewing the aid offer is displayed
And ensure all the cost of attendance fields are pre-populated
And ensure the graduation rate graph is populated
And ensure the average salary after graduation graph is populated
And ensure the total debt after graduation graph is populated
And ensure the loan default rate graph is populated

**Comment by ascott1** [comment]
This is great @marteki!

**Comment by higs4281** [comment]
excellent! are we intending to write the tests in js or behave/selenium?

**Comment by marteki** [comment]
Protractor + Jasmine, like v1 and a few other teams. So written in JS, but comes with a Selenium web driver and can be hooked up to Jenkins/Sauce/whatever.

**Comment by marteki** [comment]
# All students functional test scenarios - reviewing an offer

> As a student,
> I want to review my first-year financial aid offer

### Scenario: Student modifies tuition and fees

Given the student is reviewing their aid offer
When the student modifies their tuition and fees
Then ensure the total cost of attendance is recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies housing and meals

Given the student is reviewing their aid offer
When the student modifies their housing and meals
Then ensure the total cost of attendance is recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies transportation

Given the student is reviewing their aid offer
When the student modifies their transportation costs
Then ensure the total cost of attendance is recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies books and supplies

Given the student is reviewing their aid offer
When the student modifies their books and supplies
Then ensure the total cost of attendance is recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies other education costs

Given the student is reviewing their aid offer
When the student modifies their other education costs
Then ensure the total cost of attendance is recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies Federal Pell Grant within the grant limits

Given the student is reviewing their aid offer
When the student modifies their Federal Pell Grant within the grant limits
Then ensure the total grants and scholarships are recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies Federal Pell Grant above the grant limits

Given the student is reviewing their aid offer
When the student modifies their Federal Pell Grant above the grant limits
Then ensure that the student is informed about the cap on the grant amount
And ensure that the Federal Pell Grant amount is changed to the grant cap
And ensure the total grants and scholarships are recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies grants and scholarships from their school

Given the student is reviewing their aid offer
When the student modifies their grants and scholarships from their school
Then ensure the total grants and scholarships is recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies grants and scholarships from their state

Given the student is reviewing their aid offer
When the student modifies their grants and scholarships from their state
Then ensure the total grants and scholarships is recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies other grants and scholarships

Given the student is reviewing their aid offer
When the student modifies their other grants and scholarships
Then ensure the total grants and scholarships is recalculated correctly
And ensure the total cost is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies cash they will provide

Given the student is reviewing their aid offer
When the student modifies the cash they will provide
Then ensure the cash they will provide is recalculated correctly
And ensure the total contributions is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies cash their family will provide

Given the student is reviewing their aid offer
When the student modifies the cash their family will provide
Then ensure the cash they will provide is recalculated correctly
And ensure the total contributions is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies work study earnings within the allowed limit

Given the student is reviewing their aid offer
When the student modifies their planned work study earnings within the allowed limit
Then ensure the work study earnings are recalculated correctly
And ensure the total contributions is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies work study earnings above the allowed limit

Given the student is reviewing their aid offer
When the student modifies their planned work study earnings above the allowed limit
Then ensure that the student is informed about the cap on work study earnings
And ensure that the work study earnings amount is changed to the earnings allowed limit
Then ensure the work study earnings are recalculated correctly
And ensure the total contributions is recalculated correctly
And ensure the remaining cost is recalculated correctly

### Scenario: Student modifies their federal Perkins loans within the allowed limit

Given the student is reviewing their aid offer
When the student modifies their federal Perkins loan within the allowed limit
Then ensure the federal Perkins loan amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies their federal Perkins loans above the allowed limit

Given the student is reviewing their aid offer
When the student modifies their federal Perkins loan above the allowed limit
Then ensure that the student is informed about the cap on federal Perkins loans
And ensure that the federal Perkins loan amount is changed to the allowed limit
Then ensure the federal Perkins loan amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies their federal subsidized loans within the allowed limit

Given the student is reviewing their aid offer
When the student modifies their federal subsidized loans above the allowed limit
Then ensure the federal subsidized loan amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies their federal subsidized loans above the allowed limit

Given the student is reviewing their aid offer
When the student modifies their federal subsidized loans above the allowed limit
Then ensure that the student is informed about the cap on federal subsidized loans
And ensure that the federal subsidized loan amount is changed to the allowed limit
Then ensure the federal subsidized loan amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies their federal unsubsidized loans within the allowed limit

Given the student is reviewing their aid offer
When the student modifies their federal unsubsidized loans above the allowed limit
Then ensure the federal unsubsidized loan amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies their federal unsubsidized loans above the allowed limit

Given the student is reviewing their aid offer
When the student modifies their federal unsubsidized loans above the allowed limit
Then ensure that the student is informed about the cap on federal unsubsidized loans
And ensure that the federal unsubsidized loan amount is changed to the allowed limit
Then ensure the federal unsubsidized loan amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies their federal Direct PLUS loans within the allowed limit

Given the student is reviewing their aid offer
When the student modifies their federal Direct PLUS loans above the allowed limit
Then ensure the federal Direct PLUS loan amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies their federal Direct PLUS loans above the allowed limit

Given the student is reviewing their aid offer
When the student modifies their federal Direct PLUS loans above the allowed limit
Then ensure that the student is informed about the cap on federal Direct PLUS loans
And ensure that the federal Direct PLUS loan amount is changed to the allowed limit
Then ensure the federal Direct PLUS loan amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies a private loan amount

Given the student is reviewing their aid offer
When the student modifies a private loan amount
Then ensure the private loans and payment plans amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies a private loan interest rate

Given the student is reviewing their aid offer
When the student modifies a private loan interest rate
Then ensure the private loan interest rate is greater than zero
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student modifies a private loan grace period

Given the student is reviewing their aid offer
When the student modifies a private loan grace period
Then ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

### Scenario: Student deletes a private loan

Given the student is reviewing their aid offer
When the student deletes a private loan
Then ensure the private loans and payment plans amount is recalculated correctly
And ensure the total debt is recalculated correctly
And ensure the remaining cost is recalculated correctly
And ensure the loans for the first year are recalculated correctly
And ensure the loans for the program length are recalculated correctly
And ensure the total cost of repayment with interest is recalculated correctly
AND ensure the estimated debt burden is recalculated correctly
AND ensure the estimated monthly expense for student loans is recalculated correctly

**Comment by niqjohnson** [comment]
The review offer scenarios are looking great!

The only thing that might be missing is that when any loans are modified in step 1, both the debt burden and expenses in step 2 also have to be recalculated correctly. Not sure if that fits in here or in scenarios for step 2, though.

**Comment by marteki** [comment]
Super sharp catch, @niqjohnson; I thought of that earlier, then forgot to include them.

They should be in these scenarios as they're triggered by interactions in Step 1. I updated the above comment with added things to "AND ensure".

**Comment by marteki** [comment]
The last large chunk of scenarios. There'll be additions later, I'm sure, to test that stuff is actually coming through in the first place and around printing and other interactions we decide upon.

# All students functional test scenarios - evaluating an offer

> As a student,
> I want to evaluate my financial aid offer

### Scenario: Student modifies estimated mortgage or rent expenses

Given the student is evaluating their aid offer
When the student modifies their estimated mortgage or rent expenses
Then ensure the total monthly expenses are recalculated correctly
And ensure the amount left over is recalculated correctly

### Scenario: Student modifies estimated food expenses

Given the student is evaluating their aid offer
When the student modifies their estimated food expenses
Then ensure the total monthly expenses are recalculated correctly
And ensure the amount left over is recalculated correctly

### Scenario: Student modifies estimated transportation expenses

Given the student is evaluating their aid offer
When the student modifies their estimated transportation expenses
Then ensure the total monthly expenses are recalculated correctly
And ensure the amount left over is recalculated correctly

### Scenario: Student modifies estimated insurance expenses

Given the student is evaluating their aid offer
When the student modifies their estimated insurance expenses
Then ensure the total monthly expenses are recalculated correctly
And ensure the amount left over is recalculated correctly

### Scenario: Student modifies estimated retirement and savings expenses

Given the student is evaluating their aid offer
When the student modifies their estimated retirement or savings expenses
Then ensure the total monthly expenses are recalculated correctly
And ensure the amount left over is recalculated correctly

### Scenario: Student modifies estimated other expenses

Given the student is evaluating their aid offer
When the student modifies their estimated other expenses
Then ensure the total monthly expenses are recalculated correctly
And ensure the amount left over is recalculated correctly

### Scenario: Student thinks aid offer is a good investment in their financial future

Given the student is evaluating their aid offer
When the student says they think their aid offer is a good investment in their financial future
Then ensure the section for things to consider is displayed

### Scenario: Student thinks aid offer is not a good investment in their financial future

Given the student is evaluating their aid offer
When the student says they think their aid offer is not a good investment in their financial future
Then ensure the section for other options is displayed

### Scenario: Student is unsure if aid offer is a good investment in their financial future

Given the student is evaluating their aid offer
When the student says they are unsure if their aid offer is a good investment in their financial future
Then ensure the section for other options is displayed

**Comment by Chaeny** [comment]
Excellent work @marteki .

I have only a few minor things. 
- Do we explain what data makes up the "debt burden equation" in more detail anywhere? It’s total debt plus interest over the repayment length. We should spell it out just in case, because it satisfies two different requirements.
- For the "Student modifies grants and scholarships from their state" -  Do we need this as a category/test scenario? I didn't think we were differentiating the non-Pell grants from different sources into separate fields. I thought there was one for Pell and then one for the "Others"? Or did I misunderstand this?

**Comment by marteki** [comment]
@Chaeny -
- The information for what makes up the debt burden is spelled out on screen in the design, in a visual equation. Right now, these test scenarios are for the Javascript changes that occur when a user interacts with the tool, and are not specifically focused on spelling out requirements. There are a lot of requirements that will be met in the tool that do not need functional tests attached to them.
- In a team discussion last week, we took in feedback from Patrick and the state AGs about adding additional grant and scholarship fields, to align with the financial aid shopping sheet and the static disclosures. It's documented on an internal GitHub thread, and the design is being/has been updated. @caheberer, can you confirm that this is correct?

**Comment by marteki** [comment]
We confirmed that we will have multiple scholarship fields. Closing this for now, as a good starting point for our functional tests.
