### ISSUE TITLE
Test URLs are showing old functionality

### ISSUE THREAD

**Issue by saintsoup52** [cfpb/college-costs#303]
Short description explaining the high-level reason for the new issue.

## Current behavior
A state AG asked us for a test URL to show to a school. When I put the URL together and tested it out the tool was displaying a number of old features that should not be shown.

For example the following should not be displayed:
1) The national average bar for graduation rates
2) A warning indicator under the debt burden calculation
3) The national average for default rates

## Expected behavior
The test version should look like the current version of the tool.

## Steps to replicate behavior (include URLs)

https://www.consumerfinance.gov/paying-for-college2/understanding-your-financial-aid-offer/offer/test/?iped=482477&pid=bach&leng=48&totl=81232&tuit=19948&hous=10908&book=360&tran=0&othr=6316&pelg=5815&schg=5985&stag=0&othg=0&mta=0&gib=0&wkst=0&ppl=0&parl=0&perl=0&subl=3000&unsl=6500&gpl=0&prvl=0&prvi=0&prvf=0&insl=0&insi=0inst=0&oid=9e0280139f3238cbc9702c7b0d62e5c238a835d0#info-right

## Screenshots
![image](https://cloud.githubusercontent.com/assets/4397508/26158685/85affb16-3aea-11e7-9f8a-a3880559c825.png)

![image](https://cloud.githubusercontent.com/assets/4397508/26158709/92f6480c-3aea-11e7-9c11-05f2ae98fe8d.png)

![image](https://cloud.githubusercontent.com/assets/4397508/26158738/a0128686-3aea-11e7-981c-7e1b6cf8a5cd.png)

@higs4281

**Comment by ChristieCatan** [comment]
@saintsoup52 is sending this as an intake request to D+D to be routed.

**Comment by higs4281** [comment]
@saintsoup52 I don't see any of these problems at that URL, using Chrome, Firefox and Safari. 
I'm on the road and can't test any other browsers. Are you using IE, and if so, which version?

**Comment by rosskarchner** [comment]
@higs4281 after consultation with @mistergone , I marked that school as being part of a settlement, which seems to have resolved the issue. I followed up with @saintsoup52 via email.

**Comment by rosskarchner** [comment]
Per chuck, this is the relevant line: https://github.com/cfpb/college-costs/blob/master/src/disclosures/js/views/metric-view.js#L411

**Comment by saintsoup52** [comment]
So i tested that school it works now that it is marked as a settlement school, but I changed schools and the issue came up again.

In /test URL all the schools should be marked as settlement schools because I need to be demo any school at anytime.

And I am using chrome

**Comment by rosskarchner** [comment]
@saintsoup52 it should now work as you describe. We'll need to watch out for this the net time we update the database, or put a more permanent fix in place.
