### ISSUE TITLE
Paying for College Tool was down last night

### ISSUE THREAD

**Issue by saintsoup52** [cfpb/college-costs#304]
Short description explaining the high-level reason for the new issue.

## Current behavior
We received reports from EDMC that their students were getting an error message from the Paying for College Understanding Your Financial Aid Offer tool last night. They were receiving an 500 error code.

"The CFPB site appears to not be operational.  We are receiving many reports of students not being able to load their exercises. For context, here is a SS of the error I am getting."

## Expected behavior
That the tool would work.

## Steps to replicate behavior (include URLs)

1. None provided

## Screenshots
![image](https://cloud.githubusercontent.com/assets/4397508/26159062/91b28630-3aeb-11e7-81d0-edbc943ef272.png)

**Comment by willbarton** [comment]
This was a larger issue with the site as a whole that has been resolved.
