### ISSUE TITLE
Change "Your school" to "This school" in bar graphs

### ISSUE THREAD

**Issue by niqjohnson** [cfpb/college-costs#64]
Like the title says, "Your school" should be "This school" in all the bar graphs.

Note that there are also several references to "your school" in the non-graph content of step 2. I won't change any of those references yet, only the bar graphs for now.

**Comment by niqjohnson** [comment]
@Chaeny: Thinking about this a little more, should the new label be "This program" instead of "This school"? All three bar graphs are based on program-level data, right?

**Comment by Chaeny** [comment]
As a general rule of thumb this should say "This program" when showing program level data. 

In cases where we don't have the program level info, we switch to school level info, right?  In those cases, it should say "This school".

**Comment by higs4281** [comment]
using school data if program data isn't there should happen on the page, because the API just delivers what we have for school and program without parsing through it. 

If anyone wants this checking to happen server-side, let me know.

**Comment by niqjohnson** [comment]
Ah, I forgot that graphs will fall back to school data if program data is unavailable.

@higs4281, does the API tell you if the number it returns is school level or program level?

Either way, I suggest starting simple with static labels of "This school." Then, as time allows, we can enhance so that the labels change to "This program" if the graphs are using program data. Sound like a plan for now?

**Comment by higs4281** [comment]
When the page loads, schoolData and programData objects are delivered,
holding whatever data we have.

the comparable fields names are not currently matched well. we should fix
that.

**Comment by saintsoup52** [comment]
@niqjohnson +1

**Comment by marteki** [comment]
> Either way, I suggest starting simple with static labels of "This school."

Going with this for now. Future enhancements later.
