### ISSUE TITLE
Private Loans, bug when adding then deleting

### ISSUE THREAD

**Issue by mistergone** [cfpb/college-costs#66]
> I'm seeing a console error of Uncaught TypeError: Cannot read property 'amount' of undefined if I  follow these (admittedly unlikely) steps, though:
> - Add a second private loan
> - Remove the first private loan
> - Change the value of any of the remaining private loan fields

This is related to the way the page collects information about the private loan fields, and how those fields are updated. A special operation must be added to handle a user removing a school.

**Comment by marteki** [comment]
Fixed!
