### ISSUE TITLE
BUG: Debt data not populating

### ISSUE THREAD

**Issue by ErieMeyer** [cfpb/college-costs#89]
Hi!

The debt portion of college cost comparison tool doesn't seem to be populating. To recreate, I'm on chrome on a mac, and was comparing American University, Brown University, and Boston College.

Screenshot below!

![screen shot 2016-02-03 at 11 19 06 am](https://cloud.githubusercontent.com/assets/1626026/12788681/8836a2ac-ca68-11e5-8fdd-23b833edad42.png)

**Comment by kurzn** [comment]
@ErieMeyer Did you enter anything under the loan portion of the tool? That's where all the debt portion pulls its data from. If your loans are zero, your debt is also zero.

**Comment by ErieMeyer** [comment]
Aaah -- I thought if you didn't add it in you would see averages (like the section below) from collegescorecard.ed.gov/data

Thank you!

**Comment by kurzn** [comment]
Nope, doesn't work quite the same. You're welcome!
