### ISSUE TITLE
Leading zeros getting chopped off in school ZIPs

### ISSUE THREAD

**Issue by niqjohnson** [cfpb/college-costs#90]
Leading zeros are getting chopped off of school ZIPs in `schoolData.zip5`.

For example, Yale (IPEDS 130794) has a ZIP of 06520, but `schoolData.zip5` is 6520.

**Comment by higs4281** [comment]
fixed. pull in latest master and run loaddata.

**Comment by niqjohnson** [comment]
:+1:

Fixed it right up. Thanks, @higs4281!
